services:
  api:
    build: .
    container_name: ia-agents-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    restart: unless-stopped


